const TRAITS=[{id:"froid",label:"Cold"},{id:"tetu",label:"Stubborn"},{id:"loyal",label:"Loyal"},{id:"moqueur",label:"Mocking"},{id:"mefiant",label:"Wary"},{id:"ardent",label:"Ardent"}];
const LINES={pointe:{name:"Point",img:"pointe",skills:[{id:"ligne",name:"Line",hint:"A",dmg:8,cost:"a"},{id:"mesure",name:"Measure",hint:"B",dmg:0,cost:"b"},{id:"ouverture",name:"Opening",hint:"C",dmg:22,cost:"c"}]},taille:{name:"Edge",img:"taille",skills:[{id:"passage",name:"Passage",hint:"A",dmg:10,cost:"a"},{id:"pression",name:"Pressure",hint:"B",dmg:4,cost:"b"},{id:"rupture",name:"Rupture",hint:"C",dmg:24,cost:"c"}]},garde:{name:"Guard",img:"garde",skills:[{id:"plaque",name:"Plate",hint:"A",dmg:3,cost:"a"},{id:"rendre",name:"Return",hint:"B",dmg:12,cost:"b"},{id:"epuisement",name:"Drain",hint:"C",dmg:16,cost:"c"}]}};
const BOTS=[{id:"lame-neuve",name:"Newsteel",lineage:"pointe",habit:"Spams Line.",win:"You measured.",lose:"I am still standing.",open:"A new blade.",skillBias:["ligne","mesure"]},{id:"brume",name:"Mist",lineage:"pointe",habit:"Waits.",win:"Too early.",lose:"Should have left measure.",open:"Mist does not move.",skillBias:["mesure","ligne"]},{id:"croc",name:"Fang",lineage:"taille",habit:"Rupture under 40%.",win:"Still standing.",lose:"You waited.",open:"Fang is coming.",skillBias:["passage","rupture"]},{id:"halte",name:"Halt",lineage:"garde",habit:"Returns on second A.",win:"Tomorrow.",lose:"The wall holds.",open:"Halt plants feet.",skillBias:["plaque","rendre"]},{id:"sillage",name:"Wake",lineage:"taille",habit:"Pressure after B.",win:"You kept B.",lose:"Tempo.",open:"Wake hunts.",skillBias:["pression","passage"]},{id:"duelle",name:"Duelle",lineage:"pointe",habit:"Opening on C.",win:"Almost.",lose:"I read it.",open:"Duelle smiles.",skillBias:["ligne","ouverture"]},{id:"masse",name:"Mass",lineage:"garde",habit:"Feeds Drain.",win:"Not empty.",lose:"You fed me.",open:"Mass takes the hit.",skillBias:["plaque","epuisement"]},{id:"estoc-noir",name:"Black Estoc",lineage:"pointe",habit:"Reads favorite.",win:"You varied.",lose:"Predictable.",open:"This week's steel.",skillBias:["ligne","mesure","ouverture"]}];
const SUGGEST={pointe:"Linen",taille:"Cinder",garde:"Somme"};
const MATCH_SECS=480,SAVE_KEY="estoc.v4",LOG_KEY="estoc.log.v1";
function asset(k){return (window.ESTOC_ASSETS||{})[k]||"";}
function testerId(){let id=localStorage.getItem("estoc.tid");if(!id){id="t-"+Math.random().toString(36).slice(2,8);localStorage.setItem("estoc.tid",id);}return id;}
function dawnKey(off){const d=new Date();if(d.getHours()<4)d.setDate(d.getDate()-1);if(off)d.setDate(d.getDate()+off);return d.toISOString().slice(0,10);}
function note(kind,extra){const log=JSON.parse(localStorage.getItem(LOG_KEY)||"[]");log.push({t:new Date().toISOString(),kind,extra:extra||"",dawn:dawnKey()});localStorage.setItem(LOG_KEY,JSON.stringify(log.slice(-80)));}
function reportText(){const log=JSON.parse(localStorage.getItem(LOG_KEY)||"[]");const dawns=[...new Set(log.map(x=>x.dawn))];const sends=log.filter(x=>x.kind==="send").length;return ["Estoc 14-day report","id "+testerId(),"name "+state.name,`streak ${state.streak} wins ${state.wins} missed ${state.missed}`,`sends ${sends} dawns ${dawns.length}`].join("\n");}
const state={lineage:"pointe",traits:[],name:"Linen",ai:true,plus:false,credits:0,gestures:3,talksLeft:1,sendFree:1,lastDawn:"",lastSendDawn:"",streak:0,missed:0,weekSends:[],drillBuff:false,wounded:false,memory:[],wins:0,ladder:0,hp:100,foe:100,elanYou:0,elanFoe:0,time:MATCH_SECS,usedC:false,lastA:0,guard:0,foeGuard:0,botId:"lame-neuve",live:false};
let tick=null;
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify({lineage:state.lineage,traits:state.traits,name:state.name,ai:state.ai,plus:state.plus,credits:state.credits,gestures:state.gestures,talksLeft:state.talksLeft,sendFree:state.sendFree,lastDawn:state.lastDawn,lastSendDawn:state.lastSendDawn,streak:state.streak,missed:state.missed,weekSends:state.weekSends,drillBuff:state.drillBuff,wounded:state.wounded,memory:state.memory,wins:state.wins,ladder:state.ladder}));}
function load(){try{const raw=JSON.parse(localStorage.getItem(SAVE_KEY)||"null");if(!raw)return false;Object.assign(state,raw);return true;}catch{return false;}}
function gestureCap(){return state.plus?8:3;}
function applyDawn(force){const today=dawnKey();if(!force&&state.lastDawn===today)return;let gap=0;if(state.lastDawn){const a=new Date(state.lastDawn+"T12:00:00"),b=new Date(today+"T12:00:00");gap=Math.max(0,Math.round((b-a)/86400000)-1);}state.missed=gap;if(gap>=1)state.wounded=true;if(gap>=3&&state.memory.length)state.memory=state.memory.slice(0,-1);if(state.lastSendDawn&&state.lastSendDawn!==dawnKey(-1)&&state.lastSendDawn!==today)state.streak=0;state.gestures=gestureCap();state.talksLeft=state.plus?3:1;state.sendFree=1;state.lastDawn=today;save();}
function sendsLeft(){return state.sendFree+state.credits;}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("on"));document.getElementById(id).classList.add("on");}
function traitLabel(id){return (TRAITS.find(t=>t.id===id)||{label:id}).label;}
function remember(text){state.memory=[text.slice(0,80),...state.memory.filter(m=>m!==text)].slice(0,3);save();}
function currentBot(){return BOTS[Math.min(state.ladder,BOTS.length-1)];}
function renderTraits(){const box=document.getElementById("traits");box.innerHTML=TRAITS.map(t=>`<button class="chip ${state.traits.includes(t.id)?"on":""}" data-t="${t.id}">${t.label}</button>`).join("");box.querySelectorAll("button").forEach(b=>b.onclick=()=>{const id=b.dataset.t;if(state.traits.includes(id))state.traits=state.traits.filter(x=>x!==id);else if(state.traits.length<3)state.traits.push(id);renderTraits();});}
function phraseCamp(){if(state.missed>=2)return "The mask waited.";if(state.memory[0])return "I do not forget. "+state.memory[0];return "Camp is quiet. Send me.";}
function enterCamp(){stopClock();applyDawn(false);const L=LINES[state.lineage],bot=currentBot();document.getElementById("campName").textContent=state.name;document.getElementById("campMeta").textContent=L.name+" · "+(state.traits.map(traitLabel).join(" · ")||"—");document.getElementById("campActions").textContent="Gestures "+state.gestures+"/"+gestureCap();document.getElementById("campStreak").textContent=state.streak?"Streak "+state.streak:"Dawn";document.getElementById("campQueue").textContent=(state.sendFree?"Send ready":"Send spent")+" · vs "+bot.name;document.getElementById("campRust").textContent=state.wounded?"Rust":"";document.getElementById("campLine").textContent=phraseCamp();const sendBtn=document.getElementById("sendBtn");sendBtn.disabled=sendsLeft()<=0;sendBtn.textContent=sendsLeft()>0?"Send":"No send left";show("camp");}
function renderFiche(){document.getElementById("memList").innerHTML=state.memory.length?state.memory.map(m=>`<p class="bubble">${m}</p>`).join(""):`<p class="bubble">No yard carved yet.</p>`;document.getElementById("ficheName").textContent=state.name;document.getElementById("ladderList").innerHTML=BOTS.map((b,i)=>`<li class="${i===state.ladder?"now":""}">${b.name}</li>`).join("");}
function renderYou(){document.getElementById("youStats").textContent=(state.plus?"Plus":"Free")+" · streak "+state.streak+" · missed "+state.missed;}
function spendSend(){if(state.sendFree>0)state.sendFree-=1;else if(state.credits>0)state.credits-=1;else return false;const today=dawnKey();if(state.lastSendDawn!==today)state.streak=(state.lastSendDawn===dawnKey(-1)||!state.lastSendDawn)?state.streak+1:1;state.lastSendDawn=today;if(!state.weekSends.includes(today))state.weekSends.push(today);save();return true;}
function startDuel(){applyDawn(false);if(sendsLeft()<=0||!spendSend()){show("shop");return;}const bot=currentBot(),L=LINES[state.lineage];state.hp=state.wounded?82:100;state.foe=100;state.elanYou=0;state.elanFoe=0;state.time=MATCH_SECS;state.usedC=false;state.live=true;state.botId=bot.id;document.getElementById("youLabel").textContent=state.name;document.getElementById("foeLabel").textContent=bot.name;document.getElementById("habit").textContent=bot.habit;document.getElementById("skills").innerHTML=L.skills.map(s=>`<button data-s="${s.id}">${s.name}<small>${s.hint}</small></button>`).join("");document.getElementById("skills").querySelectorAll("button").forEach(b=>b.onclick=()=>playerSkill(b.dataset.s));note("send",bot.name);paintDuel(bot.open);show("duel");stopClock();tick=setInterval(onTick,1000);}
function stopClock(){if(tick)clearInterval(tick);tick=null;state.live=false;}
function onTick(){if(!state.live)return;state.time-=1;if(state.time<=0){finish(state.hp>=state.foe,"time");return;}if(state.time%4===0)botAct();paintDuel();}
function fmt(sec){return Math.floor(sec/60)+":"+String(sec%60).padStart(2,"0");}
function paintDuel(msg){if(msg)document.getElementById("log").textContent=msg;document.getElementById("youHp").style.width=Math.max(0,state.hp)+"%";document.getElementById("foeHp").style.width=Math.max(0,state.foe)+"%";document.getElementById("timer").textContent=fmt(state.time);}
function applyHit(target,raw){if(target==="foe"){state.foe=Math.max(0,state.foe-raw);state.elanYou+=Math.ceil(raw*0.6);}else{state.hp=Math.max(0,state.hp-raw);state.elanFoe+=Math.ceil(raw*0.6);}}
function playerSkill(id){if(!state.live)return;const def=LINES[state.lineage].skills.find(s=>s.id===id);if(!def)return;if(def.cost==="c"){if(state.usedC)return;state.usedC=true;}applyHit("foe",def.dmg);if(state.foe<=0){finish(true,id);return;}paintDuel(def.name+".");}
function botAct(){const bot=currentBot();const def=LINES[bot.lineage].skills[0];applyHit("you",Math.max(4,def.dmg-2));if(state.hp<=0)finish(false,"hit");}
function finish(win){stopClock();const bot=currentBot();if(win){state.wins+=1;state.wounded=false;if(state.ladder<BOTS.length-1)state.ladder+=1;remember("Win against "+bot.name);}else{state.wounded=true;remember("Loss vs "+bot.name);}save();document.getElementById("resTitle").textContent=win?"Victory":"Defeat";document.getElementById("resLine").textContent=bot.name+": “"+(win?bot.lose:bot.win)+"”";document.getElementById("resMem").textContent=state.memory[0]||"";document.getElementById("sendAgain").style.display=sendsLeft()>0?"block":"none";note(win?"win":"loss",bot.name);show("result");}
function doAct(act){applyDawn(false);if(state.gestures<=0){show("shop");return;}state.gestures-=1;if(act==="heal")state.wounded=false;if(act==="drill")remember("Morning drill held");document.getElementById("campLine").textContent=act==="talk"?phraseCamp():act==="drill"?"Drill held.":"The steel quiets.";document.getElementById("campActions").textContent="Gestures "+state.gestures+"/"+gestureCap();note(act);save();}
function bind(){document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{const to=b.dataset.go;if(to==="camp")enterCamp();else if(to==="duel")startDuel();else if(to==="fiche"){renderFiche();show("fiche");}else show(to);});document.querySelectorAll(".pick").forEach(c=>c.onclick=()=>{document.querySelectorAll(".pick").forEach(x=>x.classList.remove("on"));c.classList.add("on");state.lineage=c.dataset.line;state.name=SUGGEST[state.lineage];document.getElementById("name").value=state.name;});document.getElementById("name").oninput=e=>{state.name=e.target.value.slice(0,12)||SUGGEST[state.lineage];};document.getElementById("allowAi").onclick=()=>{state.ai=true;show("create");};document.getElementById("denyAi").onclick=()=>{state.ai=false;show("create");};document.getElementById("enter").onclick=()=>{if(state.traits.length!==3){alert("Three traits.");return;}applyDawn(true);note("create");save();enterCamp();};document.querySelectorAll("[data-act]").forEach(b=>b.onclick=()=>doAct(b.dataset.act));document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{const id=t.dataset.tab;if(id==="camp")enterCamp();else if(id==="fiche"){renderFiche();show("fiche");}else{if(id==="toi")renderYou();show(id);}});document.getElementById("sendAgain").onclick=()=>startDuel();document.getElementById("togglePlus").onclick=()=>{state.plus=!state.plus;save();renderYou();};document.getElementById("skipDawn").onclick=()=>{state.missed+=1;state.wounded=true;state.sendFree=1;state.gestures=gestureCap();save();enterCamp();};document.getElementById("wipe").onclick=()=>{localStorage.removeItem(SAVE_KEY);location.reload();};const copyBtn=document.getElementById("copyReport");if(copyBtn)copyBtn.onclick=async()=>{try{await navigator.clipboard.writeText(reportText());copyBtn.textContent="Report copied";}catch{alert(reportText());}};note("open");renderTraits();if(load()&&state.traits.length===3){applyDawn(false);enterCamp();}else show("splash");}
bind();
